fix the bug - the problem was on html
Uncaught Error: [$injector:modulerr] Failed to instantiate module
BreakTheCode due to:
Error: [$injector:nomod] Module 'BreakTheCode' is
not available! You either misspelled the module name or forgot to load
it. If registering a module ensure that you specify the dependencies as
the second argument.